package fr.proutlost.worldprep.gametest;

import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.plan.PlanIdentity;
import fr.proutlost.worldprep.runtime.BiomeRuntime;
import fr.proutlost.worldprep.runtime.MinecraftTerrainSampler;
import fr.proutlost.worldprep.runtime.WorldPrepRuntime;
import net.minecraft.core.BlockPos;
import net.minecraft.core.QuartPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;

import java.util.UUID;

@GameTestHolder("proutlost")
@PrefixGameTestTemplate(false)
public final class WorldPrepBiomeGameTests {
    private static final String TEMPLATE="village/plains/houses/plains_small_house_1";
    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void actualBiomeWriteProtectedExclusionAndExactRollback(GameTestHelper helper){var level=helper.getLevel();BlockPos pos=helper.absolutePos(new BlockPos(2,2,2));int qx=QuartPos.fromBlock(pos.getX()),qz=QuartPos.fromBlock(pos.getZ()),qy=QuartPos.fromBlock(pos.getY());var d=WorldPrepRuntime.data(level);String areaId="proutlost:gametest_"+UUID.randomUUID().toString().replace("-","");var area=new WorldPrepSavedData.Area(areaId,level.dimension().location().toString(),qx<<2,qz<<2,(qx<<2)+7,(qz<<2)+3);d.areas().put(areaId,area);var input=PlanIdentity.capture(level,d,area);String original=BiomeRuntime.biomeId(level,qx,qy,qz);String target=original.equals("minecraft:desert")?"minecraft:plains":"minecraft:desert";var sample=MinecraftTerrainSampler.sample(level,(qx<<2)+2,(qz<<2)+2);var plan=new WorldPrepSavedData.Plan(areaId,input,"gametest-fingerprint");var cell=new WorldPrepSavedData.BiomeCell(qx,qz,target,sample.signature());plan.cells.put(WorldPrepSavedData.cellKey(qx,qz),cell);d.plans().put(areaId,plan);UUID applyJob=UUID.randomUUID(),snapshotId=UUID.randomUUID();var snapshot=new WorldPrepSavedData.Snapshot(snapshotId,applyJob,area.dimension(),areaId,"BIOMES",plan.fingerprint);d.snapshots().put(snapshotId,snapshot);String unrelated=BiomeRuntime.biomeId(level,qx+1,qy,qz);if(!WorldPrepRuntime.applyPlannedCell(level,d,area,plan,snapshot,cell))helper.fail("eligible cell unexpectedly protected");if(!BiomeRuntime.biomeId(level,qx,qy,qz).equals(target))helper.fail("real chunk biome palette was not mutated");var changedChunk=level.getChunk(pos.getX()>>4,pos.getZ()>>4);if(!changedChunk.isUnsaved())helper.fail("changed chunk was not marked unsaved");level.getChunkSource().save(true);if(!BiomeRuntime.biomeId(level,qx,qy,qz).equals(target))helper.fail("biome was lost across real chunk save");if(!BiomeRuntime.biomeId(level,qx+1,qy,qz).equals(unrelated))helper.fail("unrelated quart cell changed");for(var saved:snapshot.cells.values())BiomeRuntime.restoreOwnedCell(level,saved);if(!BiomeRuntime.biomeId(level,qx,qy,qz).equals(original))helper.fail("exact rollback did not restore original biome");d.protections().put("test",new WorldPrepSavedData.ProtectedZone("test",area.dimension(),qx<<2,qz<<2,(qx<<2)+3,(qz<<2)+3));var protectedInput=PlanIdentity.capture(level,d,area);var protectedPlan=new WorldPrepSavedData.Plan(areaId,protectedInput,"protected-fingerprint");var protectedCell=new WorldPrepSavedData.BiomeCell(qx,qz,target,MinecraftTerrainSampler.sample(level,(qx<<2)+2,(qz<<2)+2).signature());var protectedSnapshot=new WorldPrepSavedData.Snapshot(UUID.randomUUID(),UUID.randomUUID(),area.dimension(),areaId,"BIOMES",protectedPlan.fingerprint);if(WorldPrepRuntime.applyPlannedCell(level,d,area,protectedPlan,protectedSnapshot,protectedCell))helper.fail("protected cell was reported as changed");if(!BiomeRuntime.biomeId(level,qx,qy,qz).equals(original))helper.fail("protected biome changed");helper.succeed();}
    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void controlledApplyFailurePreservesCursorAndSnapshot(GameTestHelper helper){var level=helper.getLevel();BlockPos pos=helper.absolutePos(new BlockPos(2,2,2));int qx=QuartPos.fromBlock(pos.getX()),qz=QuartPos.fromBlock(pos.getZ());var d=WorldPrepRuntime.data(level);String areaId="proutlost:failure_"+UUID.randomUUID().toString().replace("-","");var area=new WorldPrepSavedData.Area(areaId,level.dimension().location().toString(),qx<<2,qz<<2,(qx<<2)+7,(qz<<2)+3);d.areas().put(areaId,area);var input=PlanIdentity.capture(level,d,area);var plan=new WorldPrepSavedData.Plan(areaId,input,"failure-fingerprint");String target="minecraft:desert";var first=MinecraftTerrainSampler.sample(level,(qx<<2)+2,(qz<<2)+2);var second=MinecraftTerrainSampler.sample(level,((qx+1)<<2)+2,(qz<<2)+2);plan.cells.put(WorldPrepSavedData.cellKey(qx,qz),new WorldPrepSavedData.BiomeCell(qx,qz,target,first.signature()));plan.cells.put(WorldPrepSavedData.cellKey(qx+1,qz),new WorldPrepSavedData.BiomeCell(qx+1,qz,target,second.signature()+1));d.plans().put(areaId,plan);UUID job=WorldPrepRuntime.enqueue(level,WorldPrepSavedData.Operation.APPLY_BIOMES,areaId);helper.runAfterDelay(3,()->{var failed=d.jobs().get(job);if(failed.state()!=WorldPrepSavedData.JobState.FAILED)helper.fail("job did not enter FAILED");if(failed.cursor()!=1)helper.fail("successful cursor was not preserved");if(failed.error().isBlank()||!failed.error().contains("PREVIEW STALE"))helper.fail("failure context missing");var snapshot=d.snapshots().get(failed.snapshotId());if(snapshot==null||snapshot.cells.isEmpty())helper.fail("rollback snapshot was not preserved");for(var cell:snapshot.cells.values())BiomeRuntime.restoreOwnedCell(level,cell);helper.succeed();});}
    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void administratorCommandDispatcherSurface(GameTestHelper helper){var server=helper.getLevel().getServer();var dispatcher=server.getCommands().getDispatcher();var root=dispatcher.getRoot().getChild("proutlost");if(root==null||root.getChild("worldprep")==null)helper.fail("WorldPrep command root missing");var wp=root.getChild("worldprep");for(String name:new String[]{"pos1","pos2","area","analyze","preview","inspect","apply","status","pause","resume","cancel","rollback"})if(wp.getChild(name)==null)helper.fail("Missing command "+name);var area=wp.getChild("area");for(String name:new String[]{"create","info","list","delete"})if(area.getChild(name)==null)helper.fail("Missing area command "+name);var source=server.createCommandSourceStack();server.getCommands().performPrefixedCommand(source,"proutlost worldprep status");server.getCommands().performPrefixedCommand(source,"proutlost worldprep area list");var malformed=dispatcher.parse("proutlost worldprep apply biomes",source);if(malformed.getContext().getCommand()!=null)helper.fail("malformed apply unexpectedly parsed as executable");helper.succeed();}
    private WorldPrepBiomeGameTests(){}
}
