package fr.proutlost.worldprep.gametest;

import fr.proutlost.worldprep.persistence.BlockWorldPrepData;
import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.runtime.BlockMutationRuntime;
import fr.proutlost.worldprep.runtime.WorldPrepRuntime;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;

import java.util.UUID;

@GameTestHolder("proutlost")
@PrefixGameTestTemplate(false)
public final class WorldPrepBlockGameTests {
    private static final String TEMPLATE="village/plains/houses/plains_small_house_1";

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void geologyApplyUsesRealRuntimeAndLeavesUnrelatedBlock(GameTestHelper h){var c=context(h,"geology_apply");var changed=h.absolutePos(new BlockPos(2,2,2));var unrelated=h.absolutePos(new BlockPos(3,2,2));c.level.setBlockAndUpdate(changed,Blocks.STONE.defaultBlockState());c.level.setBlockAndUpdate(unrelated,Blocks.GOLD_BLOCK.defaultBlockState());var p=plan(c,"GEOLOGY");change(p,changed,"minecraft:stone","minecraft:granite","GRANITIC");apply(c,p,WorldPrepSavedData.Operation.APPLY_GEOLOGY);check(c.level.getBlockState(changed).is(Blocks.GRANITE),h,"geology did not mutate real BlockState");check(c.level.getBlockState(unrelated).is(Blocks.GOLD_BLOCK),h,"unrelated block changed");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void geologyProtectionExcludesProtectedButAllowsEligible(GameTestHelper h){var c=context(h,"geology_protection");var protectedPos=h.absolutePos(new BlockPos(2,2,2));var open=h.absolutePos(new BlockPos(3,2,2));c.level.setBlockAndUpdate(protectedPos,Blocks.STONE.defaultBlockState());c.level.setBlockAndUpdate(open,Blocks.STONE.defaultBlockState());c.data.protections().put(c.id,new WorldPrepSavedData.ProtectedZone(c.id,c.area.dimension(),protectedPos.getX(),protectedPos.getZ(),protectedPos.getX(),protectedPos.getZ()));var p=plan(c,"GEOLOGY");change(p,protectedPos,"minecraft:stone","minecraft:tuff","TUFF_RICH");change(p,open,"minecraft:stone","minecraft:andesite","MIXED_STONE");apply(c,p,WorldPrepSavedData.Operation.APPLY_GEOLOGY);check(c.level.getBlockState(protectedPos).is(Blocks.STONE),h,"protected geology changed");check(c.level.getBlockState(open).is(Blocks.ANDESITE),h,"unprotected geology did not change");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void geologyRollbackRestoresExactOriginalState(GameTestHelper h){var c=context(h,"geology_rollback");var pos=h.absolutePos(new BlockPos(2,2,2));c.level.setBlockAndUpdate(pos,Blocks.STONE.defaultBlockState());var p=plan(c,"GEOLOGY");change(p,pos,"minecraft:stone","minecraft:diorite","MIXED_STONE");apply(c,p,WorldPrepSavedData.Operation.APPLY_GEOLOGY);check(c.level.getBlockState(pos).is(Blocks.DIORITE),h,"geology apply absent");run(c,WorldPrepRuntime.enqueue(c.level,WorldPrepSavedData.Operation.ROLLBACK_GEOLOGY,c.id));check(c.level.getBlockState(pos).is(Blocks.STONE),h,"exact geology rollback failed");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void oreApplyHonorsHostsAndVerticalRanges(GameTestHelper h){var c=context(h,"ore_apply");orePrerequisite(c);var deep=h.absolutePos(new BlockPos(2,2,2));var stone=h.absolutePos(new BlockPos(3,70,2));var outOfRange=h.absolutePos(new BlockPos(4,100,2));c.level.setBlockAndUpdate(deep,Blocks.DEEPSLATE.defaultBlockState());c.level.setBlockAndUpdate(stone,Blocks.STONE.defaultBlockState());c.level.setBlockAndUpdate(outOfRange,Blocks.STONE.defaultBlockState());check(c.level.getBlockState(deep).is(net.minecraft.tags.BlockTags.create(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("proutlost","ore_replaceable/deepslate"))),h,"deepslate host tag missing y="+deep.getY());var p=plan(c,"ORES");change(p,deep,BlockMutationRuntime.stateString(c.level.getBlockState(deep)),"minecraft:deepslate_diamond_ore","diamond");change(p,stone,"minecraft:stone","minecraft:coal_ore","coal");change(p,outOfRange,"minecraft:stone","minecraft:diamond_ore","diamond");apply(c,p,WorldPrepSavedData.Operation.APPLY_ORES);check(c.level.getBlockState(deep).is(Blocks.DEEPSLATE_DIAMOND_ORE),h,"deepslate ore absent");check(c.level.getBlockState(stone).is(Blocks.COAL_ORE),h,"stone ore absent");check(c.level.getBlockState(outOfRange).is(Blocks.STONE),h,"out-of-range ore was placed");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void oreProtectionBlockEntityAndInvalidHostsRemain(GameTestHelper h){var c=context(h,"ore_safety");orePrerequisite(c);var protectedPos=h.absolutePos(new BlockPos(2,2,2));var chest=h.absolutePos(new BlockPos(3,2,2));var invalid=h.absolutePos(new BlockPos(4,2,2));var open=h.absolutePos(new BlockPos(5,2,2));c.level.setBlockAndUpdate(protectedPos,Blocks.DEEPSLATE.defaultBlockState());c.level.setBlockAndUpdate(chest,Blocks.CHEST.defaultBlockState());c.level.setBlockAndUpdate(invalid,Blocks.GOLD_BLOCK.defaultBlockState());c.level.setBlockAndUpdate(open,Blocks.DEEPSLATE.defaultBlockState());c.data.protections().put(c.id,new WorldPrepSavedData.ProtectedZone(c.id,c.area.dimension(),protectedPos.getX(),protectedPos.getZ(),protectedPos.getX(),protectedPos.getZ()));check(c.level.getBlockState(open).is(net.minecraft.tags.BlockTags.create(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("proutlost","ore_replaceable/deepslate"))),h,"open deepslate host tag missing y="+open.getY());var p=plan(c,"ORES");change(p,protectedPos,BlockMutationRuntime.stateString(c.level.getBlockState(protectedPos)),"minecraft:deepslate_diamond_ore","diamond");change(p,chest,BlockMutationRuntime.stateString(c.level.getBlockState(chest)),"minecraft:deepslate_diamond_ore","diamond");change(p,invalid,"minecraft:gold_block","minecraft:deepslate_diamond_ore","diamond");change(p,open,BlockMutationRuntime.stateString(c.level.getBlockState(open)),"minecraft:deepslate_redstone_ore","redstone");apply(c,p,WorldPrepSavedData.Operation.APPLY_ORES);check(c.level.getBlockState(protectedPos).is(Blocks.DEEPSLATE),h,"protected host changed");check(c.level.getBlockState(chest).is(Blocks.CHEST)&&c.level.getBlockEntity(chest)!=null,h,"block entity changed");check(c.level.getBlockState(invalid).is(Blocks.GOLD_BLOCK),h,"invalid host changed");check(c.level.getBlockState(open).is(Blocks.DEEPSLATE_REDSTONE_ORE),h,"eligible host did not change");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void oreRollbackRestoresExactHosts(GameTestHelper h){var c=context(h,"ore_rollback");orePrerequisite(c);var pos=h.absolutePos(new BlockPos(2,2,2));c.level.setBlockAndUpdate(pos,Blocks.DEEPSLATE.defaultBlockState());check(c.level.getBlockState(pos).is(net.minecraft.tags.BlockTags.create(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("proutlost","ore_replaceable/deepslate"))),h,"rollback deepslate host tag missing y="+pos.getY());var p=plan(c,"ORES");change(p,pos,BlockMutationRuntime.stateString(c.level.getBlockState(pos)),"minecraft:deepslate_diamond_ore","diamond");apply(c,p,WorldPrepSavedData.Operation.APPLY_ORES);check(c.level.getBlockState(pos).is(Blocks.DEEPSLATE_DIAMOND_ORE),h,"ore apply absent");run(c,WorldPrepRuntime.enqueue(c.level,WorldPrepSavedData.Operation.ROLLBACK_ORES,c.id));check(c.level.getBlockState(pos).is(Blocks.DEEPSLATE),h,"ore rollback did not restore host");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=40)
    public static void controlledBlockFailurePreservesJournalCursorAndRollback(GameTestHelper h){var c=context(h,"block_failure");var first=h.absolutePos(new BlockPos(2,2,2));var second=h.absolutePos(new BlockPos(3,2,2));c.level.setBlockAndUpdate(first,Blocks.STONE.defaultBlockState());c.level.setBlockAndUpdate(second,Blocks.STONE.defaultBlockState());var p=plan(c,"GEOLOGY");change(p,first,"minecraft:stone","minecraft:granite","GRANITIC");change(p,second,"minecraft:stone","not a resource id","GRANITIC");BlockMutationRuntime.seal(p);BlockMutationRuntime.data(c.level).plans().put(BlockWorldPrepData.planKey(c.id,"GEOLOGY"),p);var id=WorldPrepRuntime.enqueue(c.level,WorldPrepSavedData.Operation.APPLY_GEOLOGY,c.id);run(c,id);var failed=c.data.jobs().get(id);check(failed.state()==WorldPrepSavedData.JobState.FAILED,h,"controlled failure did not enter FAILED");check(failed.cursor()==0,h,"failed batch cursor advanced past durable checkpoint");var journal=BlockMutationRuntime.data(c.level).journals().get(failed.snapshotId());check(journal!=null&&!journal.changes.isEmpty(),h,"failure journal missing");check(c.level.getBlockState(first).is(Blocks.GRANITE),h,"failure did not occur after mutation");run(c,WorldPrepRuntime.enqueue(c.level,WorldPrepSavedData.Operation.ROLLBACK_GEOLOGY,c.id));check(c.level.getBlockState(first).is(Blocks.STONE),h,"rollback unavailable after failure");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=80)
    public static void journalFirstCrashWindowResumesIdempotently(GameTestHelper h){var c=context(h,"journal_resume");var first=h.absolutePos(new BlockPos(2,2,2));var second=h.absolutePos(new BlockPos(3,2,2));c.level.setBlockAndUpdate(first,Blocks.STONE.defaultBlockState());c.level.setBlockAndUpdate(second,Blocks.STONE.defaultBlockState());var p=plan(c,"GEOLOGY");change(p,first,"minecraft:stone","minecraft:granite","GRANITIC");change(p,second,"minecraft:stone","minecraft:diorite","MIXED_STONE");BlockMutationRuntime.seal(p);var blocks=BlockMutationRuntime.data(c.level);blocks.plans().put(BlockWorldPrepData.planKey(c.id,"GEOLOGY"),p);UUID jobId=UUID.randomUUID(),snapshotId=UUID.randomUUID();var journal=new BlockWorldPrepData.Journal(snapshotId,jobId,c.id,"GEOLOGY",p.fingerprint);journal.changes.putAll(p.changes);blocks.journals().put(snapshotId,journal);c.level.setBlockAndUpdate(first,Blocks.GRANITE.defaultBlockState());c.data.jobs().put(jobId,new WorldPrepSavedData.Job(jobId,WorldPrepSavedData.Operation.APPLY_GEOLOGY,c.id,WorldPrepSavedData.JobState.QUEUED,0,"",snapshotId));blocks.changed();c.data.changed();c.level.getDataStorage().save();run(c,jobId);check(c.level.getBlockState(first).is(Blocks.GRANITE),h,"already-applied entry was not accepted");check(c.level.getBlockState(second).is(Blocks.DIORITE),h,"journaled-before entry was not resumed");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=80)
    public static void partialBatchRollbackTreatsNeverAppliedAsNoOp(GameTestHelper h){var c=context(h,"partial_rollback");var first=h.absolutePos(new BlockPos(2,2,2));var second=h.absolutePos(new BlockPos(3,2,2));c.level.setBlockAndUpdate(first,Blocks.GRANITE.defaultBlockState());c.level.setBlockAndUpdate(second,Blocks.STONE.defaultBlockState());var p=plan(c,"GEOLOGY");change(p,first,"minecraft:stone","minecraft:granite","GRANITIC");change(p,second,"minecraft:stone","minecraft:diorite","MIXED_STONE");BlockMutationRuntime.seal(p);var blocks=BlockMutationRuntime.data(c.level);UUID snapshot=UUID.randomUUID();var journal=new BlockWorldPrepData.Journal(snapshot,UUID.randomUUID(),c.id,"GEOLOGY",p.fingerprint);journal.changes.putAll(p.changes);blocks.journals().put(snapshot,journal);blocks.changed();run(c,WorldPrepRuntime.enqueue(c.level,WorldPrepSavedData.Operation.ROLLBACK_GEOLOGY,c.id));check(c.level.getBlockState(first).is(Blocks.STONE),h,"applied entry was not restored");check(c.level.getBlockState(second).is(Blocks.STONE),h,"never-applied entry was changed");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=80)
    public static void rollbackRefusesExternalOwnershipConflict(GameTestHelper h){var c=context(h,"ownership_conflict");var pos=h.absolutePos(new BlockPos(2,2,2));c.level.setBlockAndUpdate(pos,Blocks.STONE.defaultBlockState());var p=plan(c,"GEOLOGY");change(p,pos,"minecraft:stone","minecraft:granite","GRANITIC");apply(c,p,WorldPrepSavedData.Operation.APPLY_GEOLOGY);c.level.setBlockAndUpdate(pos,Blocks.GOLD_BLOCK.defaultBlockState());UUID rollback=WorldPrepRuntime.enqueue(c.level,WorldPrepSavedData.Operation.ROLLBACK_GEOLOGY,c.id);run(c,rollback);check(c.data.jobs().get(rollback).state()==WorldPrepSavedData.JobState.FAILED,h,"ownership conflict did not fail closed");check(c.level.getBlockState(pos).is(Blocks.GOLD_BLOCK),h,"external state was overwritten");h.succeed();}

    @GameTest(templateNamespace="minecraft",template=TEMPLATE,timeoutTicks=200)
    public static void largeRealChunkPlanRunsInBoundedBatches(GameTestHelper h){var c=context(h,"large_plan");var p=plan(c,"GEOLOGY");var base=h.absolutePos(new BlockPos(1,1,1));for(int i=0;i<600;i++){var pos=new BlockPos(base.getX()+(i%9),c.level.getMinBuildHeight()+(i/27),base.getZ()+((i/9)%3));c.level.setBlockAndUpdate(pos,Blocks.STONE.defaultBlockState());change(p,pos,"minecraft:stone","minecraft:granite","GRANITIC");}apply(c,p,WorldPrepSavedData.Operation.APPLY_GEOLOGY);check(p.changes.size()==600,h,"synthetic plan was not representative");check(p.changes.values().stream().allMatch(change->c.level.getBlockState(new BlockPos(change.x(),change.y(),change.z())).is(Blocks.GRANITE)),h,"large plan did not finish");h.succeed();}

    private record Ctx(GameTestHelper helper,net.minecraft.server.level.ServerLevel level,WorldPrepSavedData data,String id,WorldPrepSavedData.Area area){}
    private static Ctx context(GameTestHelper h,String prefix){var level=h.getLevel();var d=WorldPrepRuntime.data(level);var base=h.absolutePos(new BlockPos(1,1,1));String id="proutlost:"+prefix+UUID.randomUUID().toString().replace("-","");var a=new WorldPrepSavedData.Area(id,level.dimension().location().toString(),base.getX(),base.getZ(),base.getX()+8,base.getZ()+2);d.areas().put(id,a);d.changed();return new Ctx(h,level,d,id,a);}
    private static BlockWorldPrepData.Plan plan(Ctx c,String pass){return new BlockWorldPrepData.Plan(c.id,pass,"gametest",BlockMutationRuntime.inputIdentity(c.level,c.data,c.area,pass),"");}
    private static void change(BlockWorldPrepData.Plan p,BlockPos pos,String before,String after,String kind){p.changes.put(BlockWorldPrepData.posKey(pos.getX(),pos.getY(),pos.getZ()),new BlockWorldPrepData.Change(pos.getX(),pos.getY(),pos.getZ(),before,after,kind));}
    private static void apply(Ctx c,BlockWorldPrepData.Plan p,WorldPrepSavedData.Operation operation){BlockMutationRuntime.seal(p);BlockMutationRuntime.data(c.level).plans().put(BlockWorldPrepData.planKey(c.id,p.pass),p);BlockMutationRuntime.data(c.level).changed();run(c,WorldPrepRuntime.enqueue(c.level,operation,c.id));var job=c.data.jobs().values().stream().filter(j->j.area().equals(c.id)&&j.operation()==operation).reduce((x,y)->y).orElseThrow();if(job.state()!=WorldPrepSavedData.JobState.COMPLETED)throw new AssertionError("apply job failed: "+job.error());}
    private static void orePrerequisite(Ctx c){var p=plan(c,"GEOLOGY");BlockMutationRuntime.seal(p);var bd=BlockMutationRuntime.data(c.level);bd.plans().put(BlockWorldPrepData.planKey(c.id,"GEOLOGY"),p);var id=UUID.randomUUID();bd.journals().put(id,new BlockWorldPrepData.Journal(id,UUID.randomUUID(),c.id,"GEOLOGY",p.fingerprint));bd.changed();}
    private static void run(Ctx c,UUID id){for(int i=0;i<8;i++){WorldPrepRuntime.tickLevel(c.level,1_000_000);var state=c.data.jobs().get(id).state();if(state==WorldPrepSavedData.JobState.COMPLETED||state==WorldPrepSavedData.JobState.FAILED)return;}throw new AssertionError("job did not terminate");}
    private static void check(boolean value,GameTestHelper h,String message){if(!value)h.fail(message);}
    private WorldPrepBlockGameTests(){}
}
