package fr.proutlost.worldprep;
import fr.proutlost.worldprep.analysis.TerrainAnalysis;import fr.proutlost.worldprep.area.WorldPrepArea;import fr.proutlost.worldprep.job.WorldPrepJob;import fr.proutlost.worldprep.plan.EnvironmentPlanner;import fr.proutlost.worldprep.plan.PlanFingerprint;import org.junit.jupiter.api.Test;import fr.proutlost.worldprep.biome.BiomeCandidate;import fr.proutlost.worldprep.override.ModificationPolicy;import fr.proutlost.worldprep.ore.OrePlanner;import fr.proutlost.worldprep.snapshot.ChangeJournal;import static org.junit.jupiter.api.Assertions.*;
class WorldPrepDomainTest{
 @Test void areasNormalizeNegativeCoordinates(){var a=WorldPrepArea.between("proutlost:test","minecraft:overworld",4,8,-5,-3);assertEquals(-5,a.minX());assertEquals(10,a.width());assertTrue(a.contains(-1,0));}
 @Test void analysisDerivesSlopeDepthCoastAndIgnoresBiome(){int[] h={40,40,63,64,150};boolean[] w={true,true,false,false,false};var a=TerrainAnalysis.analyze(5,1,63,h,w);assertEquals(23,a.waterDepth(0,0));assertEquals(TerrainAnalysis.Kind.DEEP_MARINE,a.classify(0,0));assertEquals(TerrainAnalysis.Kind.MOUNTAIN,a.classify(4,0));assertTrue(a.slope(3,0)>0);assertEquals(0,a.coastDistance(1,0));}
 @Test void plansAreDeterministic(){int[] h=new int[25];java.util.Arrays.fill(h,80);var a=TerrainAnalysis.analyze(5,5,63,h,new boolean[25]);assertEquals(EnvironmentPlanner.plan(a,2,2,42),EnvironmentPlanner.plan(a,2,2,42));}
 @Test void fingerprintsAreStableAndSensitive(){assertEquals(PlanFingerprint.of("a","b"),PlanFingerprint.of("a","b"));assertNotEquals(PlanFingerprint.of("a","b"),PlanFingerprint.of("a","c"));}
 @Test void jobsPauseWithoutLosingProgress(){var j=new WorldPrepJob();j.transition(WorldPrepJob.State.ANALYZING);j.advance(12);j.pause();assertEquals(12,j.cursor());j.resume();assertEquals(WorldPrepJob.State.ANALYZING,j.state());}
 @Test void biomeFallbackIsExplicit(){var c=new BiomeCandidate("missing:forest","minecraft:forest");var r=c.resolve(id->id.equals("minecraft:forest"));assertEquals(BiomeCandidate.Status.FALLBACK,r.status());assertEquals("minecraft:forest",r.resolvedId());}
 @Test void protectionHasAbsolutePrecedence(){var d=ModificationPolicy.decide(true,"minecraft:forest","coastal","planned");assertFalse(d.mutable());assertEquals(ModificationPolicy.Source.PROTECTED,d.source());}
 @Test void oreRequiresNaturalHostAndIsDeterministic(){var p=new OrePlanner.Profile("minecraft:iron_ore",-64,64,1,7,java.util.Set.of("minecraft:stone"));assertTrue(OrePlanner.shouldPlace(p,42,1,20,2,"minecraft:stone",false,false));assertFalse(OrePlanner.shouldPlace(p,42,1,20,2,"custom:brick",false,false));assertFalse(OrePlanner.shouldPlace(p,42,1,20,2,"minecraft:stone",true,false));assertFalse(OrePlanner.shouldPlace(p,42,1,20,2,"minecraft:stone",false,true));}
 @Test void snapshotRecordsOriginalOnceAndRollsBackInReverse(){var j=new ChangeJournal<String>();var p=new ChangeJournal.Position(1,2,3);j.record(p,"stone");j.record(p,"ore");j.record(new ChangeJournal.Position(2,2,3),"dirt");j.seal();assertEquals(2,j.size());assertEquals("dirt",j.reverse().getFirst().before());assertThrows(IllegalStateException.class,()->j.record(p,"x"));}
}
