package fr.proutlost.worldprep;

import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.plan.BiomeBounds;
import fr.proutlost.worldprep.plan.BiomePlanGuard;
import fr.proutlost.worldprep.plan.PlanIdentity;
import fr.proutlost.worldprep.runtime.WorldPrepRuntime;
import net.minecraft.nbt.CompoundTag;
import org.junit.jupiter.api.Test;

import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

class WorldPrepPersistenceTest {
    private static WorldPrepSavedData.PlanInput input(){return new WorldPrepSavedData.PlanInput("minecraft:overworld",-17,-9,31,48,42,"proutlost:river_test","profile","config","registry","override","protection");}
    @Test void areasPlansJobsProtectionsOverridesAndSnapshotsRoundTrip(){var data=new WorldPrepSavedData();var area=new WorldPrepSavedData.Area("proutlost:test","minecraft:overworld",-17,-9,31,48);data.areas().put(area.id(),area);UUID player=UUID.randomUUID();data.selections().put(player,new WorldPrepSavedData.Selection(-17,-9,31,48));data.protections().put("site",new WorldPrepSavedData.ProtectedZone("site","minecraft:overworld",0,0,3,3));data.overrides().put(WorldPrepSavedData.cellKey(-2,3),new WorldPrepSavedData.OverrideCell(-2,3,"minecraft:forest",null));var plan=new WorldPrepSavedData.Plan(area.id(),input(),"abc");plan.cells.put(WorldPrepSavedData.cellKey(-2,3),new WorldPrepSavedData.BiomeCell(-2,3,"minecraft:forest",99));data.plans().put(area.id(),plan);UUID jobId=UUID.randomUUID(),snapshotId=UUID.randomUUID();data.jobs().put(jobId,new WorldPrepSavedData.Job(jobId,WorldPrepSavedData.Operation.APPLY_BIOMES,area.id(),WorldPrepSavedData.JobState.PAUSED,17,"",snapshotId));var snapshot=new WorldPrepSavedData.Snapshot(snapshotId,jobId,area.dimension(),area.id(),"BIOMES","abc");snapshot.cells.put(WorldPrepSavedData.snapshotKey(-2,-16,3),new WorldPrepSavedData.SnapshotCell(-2,-16,3,"minecraft:deep_ocean","minecraft:forest"));data.snapshots().put(snapshotId,snapshot);var restored=WorldPrepSavedData.load(data.save(new CompoundTag(),null),null);assertEquals(area,restored.areas().get(area.id()));assertEquals(31,restored.selections().get(player).x2());assertTrue(restored.protectedAt(area.dimension(),0,0));assertEquals("minecraft:forest",restored.overrides().values().iterator().next().exactBiome());assertEquals(input(),restored.plans().get(area.id()).input);assertEquals(17,restored.jobs().get(jobId).cursor());assertEquals("minecraft:deep_ocean",restored.snapshots().get(snapshotId).cells.values().iterator().next().beforeBiome());}
    @Test void newerSchemaIsRejectedWithoutOverwrite(){var tag=new CompoundTag();tag.putInt("schema",WorldPrepSavedData.SCHEMA+1);assertThrows(IllegalStateException.class,()->WorldPrepSavedData.load(tag,null));}
    @Test void staleTerrainIsRejected(){BiomePlanGuard.requireCurrent(7,7);assertThrows(IllegalStateException.class,()->BiomePlanGuard.requireCurrent(7,8));}
    @Test void completePlanInputStaleMatrix(){var base=input();PlanIdentity.requireCurrent(base,base);assertStale(new WorldPrepSavedData.PlanInput("minecraft:nether",base.minX(),base.minZ(),base.maxX(),base.maxZ(),base.seed(),base.profile(),base.profileDigest(),base.configDigest(),base.registryDigest(),base.overrideDigest(),base.protectionDigest()));assertStale(new WorldPrepSavedData.PlanInput(base.dimension(),0,base.minZ(),base.maxX(),base.maxZ(),base.seed(),base.profile(),base.profileDigest(),base.configDigest(),base.registryDigest(),base.overrideDigest(),base.protectionDigest()));assertStale(change("seed"));assertStale(change("profile"));assertStale(change("profileDigest"));assertStale(change("config"));assertStale(change("registry"));assertStale(change("override"));assertStale(change("protection"));}
    private static void assertStale(WorldPrepSavedData.PlanInput changed){assertThrows(IllegalStateException.class,()->PlanIdentity.requireCurrent(input(),changed));}
    private static WorldPrepSavedData.PlanInput change(String field){var i=input();return new WorldPrepSavedData.PlanInput(i.dimension(),i.minX(),i.minZ(),i.maxX(),i.maxZ(),field.equals("seed")?43:i.seed(),field.equals("profile")?"x:y":i.profile(),field.equals("profileDigest")?"x":i.profileDigest(),field.equals("config")?"x":i.configDigest(),field.equals("registry")?"x":i.registryDigest(),field.equals("override")?"x":i.overrideDigest(),field.equals("protection")?"x":i.protectionDigest());}
    @Test void overlappingDestructiveAreaIsRejectedEvenWhilePaused(){var d=new WorldPrepSavedData();var a=new WorldPrepSavedData.Area("proutlost:a","minecraft:overworld",-10,-10,10,10);var b=new WorldPrepSavedData.Area("proutlost:b","minecraft:overworld",10,10,20,20);d.areas().put(a.id(),a);d.areas().put(b.id(),b);UUID id=UUID.randomUUID();d.jobs().put(id,new WorldPrepSavedData.Job(id,WorldPrepSavedData.Operation.APPLY_BIOMES,a.id(),WorldPrepSavedData.JobState.PAUSED,4,"",UUID.randomUUID()));assertThrows(IllegalStateException.class,()->WorldPrepRuntime.assertUnlocked(d,b));}
    @Test void snapshotOwnershipRejectsAreaDimensionPassAndFingerprintMismatch(){var area=new WorldPrepSavedData.Area("proutlost:a","minecraft:overworld",0,0,15,15);var s=new WorldPrepSavedData.Snapshot(UUID.randomUUID(),UUID.randomUUID(),area.dimension(),area.id(),"BIOMES","fp");WorldPrepRuntime.requireSnapshotOwnership(s,area,"fp");assertThrows(IllegalStateException.class,()->WorldPrepRuntime.requireSnapshotOwnership(s,new WorldPrepSavedData.Area("proutlost:b",area.dimension(),0,0,15,15),"fp"));assertThrows(IllegalStateException.class,()->WorldPrepRuntime.requireSnapshotOwnership(s,new WorldPrepSavedData.Area(area.id(),"minecraft:nether",0,0,15,15),"fp"));assertThrows(IllegalStateException.class,()->WorldPrepRuntime.requireSnapshotOwnership(s,area,"later"));}
    @Test void destructiveBoundsOnlyContainCompleteQuartCells(){for(var area:new WorldPrepSavedData.Area[]{new WorldPrepSavedData.Area("proutlost:p","minecraft:overworld",1,2,18,21),new WorldPrepSavedData.Area("proutlost:n","minecraft:overworld",-19,-18,-2,-1),new WorldPrepSavedData.Area("proutlost:c","minecraft:overworld",15,15,36,36)}){var b=BiomeBounds.inside(area);for(int z=b.minQuartZ();z<=b.maxQuartZ();z++)for(int x=b.minQuartX();x<=b.maxQuartX();x++)assertTrue(b.footprintInside(area,x,z));assertFalse(b.contains(b.minQuartX()-1,b.minQuartZ()));assertFalse(b.contains(b.maxQuartX()+1,b.maxQuartZ()));}}
    @Test void snapshotRetainsExactBeforeAndAppliedVerticalValues(){UUID id=UUID.randomUUID(),job=UUID.randomUUID();var s=new WorldPrepSavedData.Snapshot(id,job,"minecraft:overworld","proutlost:a","BIOMES","fp");s.cells.put(WorldPrepSavedData.snapshotKey(1,-16,2),new WorldPrepSavedData.SnapshotCell(1,-16,2,"minecraft:deep_ocean","minecraft:forest"));s.cells.put(WorldPrepSavedData.snapshotKey(1,-15,2),new WorldPrepSavedData.SnapshotCell(1,-15,2,"minecraft:ocean","minecraft:forest"));var data=new WorldPrepSavedData();data.snapshots().put(id,s);var restored=WorldPrepSavedData.load(data.save(new CompoundTag(),null),null).snapshots().get(id);assertEquals(s.cells,restored.cells);}
}
