package fr.proutlost.worldprep.runtime;

import fr.proutlost.worldprep.geology.GeologyPlanner;
import fr.proutlost.worldprep.persistence.BlockWorldPrepData;
import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.plan.PlanFingerprint;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.Property;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.UUID;

/** Shared incremental executor for deterministic BlockState plans and owned rollback journals. */
public final class BlockMutationRuntime {
    private static final TagKey<Block> GEOLOGY=tag("geology_replaceable"),STONE=tag("ore_replaceable/stone"),DEEPSLATE=tag("ore_replaceable/deepslate");
    private record Ore(String name,String stone,String deep,int min,int max,int rarity,long salt){}
    private static final Ore[] ORES={new Ore("coal","coal_ore","deepslate_coal_ore",0,192,95,11),new Ore("iron","iron_ore","deepslate_iron_ore",-64,128,120,17),new Ore("copper","copper_ore","deepslate_copper_ore",-16,112,150,23),new Ore("gold","gold_ore","deepslate_gold_ore",-64,32,260,29),new Ore("redstone","redstone_ore","deepslate_redstone_ore",-64,16,180,31),new Ore("lapis","lapis_ore","deepslate_lapis_ore",-64,48,300,37),new Ore("diamond","diamond_ore","deepslate_diamond_ore",-64,16,650,41),new Ore("emerald","emerald_ore","deepslate_emerald_ore",32,256,900,43)};
    public static BlockWorldPrepData data(ServerLevel l){return l.getDataStorage().computeIfAbsent(BlockWorldPrepData.FACTORY,BlockWorldPrepData.FILE_ID);}
    public static boolean isBlockOperation(WorldPrepSavedData.Operation o){return o.ordinal()>=WorldPrepSavedData.Operation.PREVIEW_GEOLOGY.ordinal();}
    public static void prepare(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Operation op,WorldPrepSavedData.Area a){String pass=pass(op);var bd=data(level);if(isApply(op)){var p=requirePlan(level,d,a,pass);var sid=UUID.randomUUID();bd.journals().put(sid,new BlockWorldPrepData.Journal(sid,id,a.id(),pass,p.fingerprint));d.jobs().put(id,d.jobs().get(id).withSnapshot(sid));bd.changed();d.changed();level.getDataStorage().save();}else if(isRollback(op)){var journal=bd.journals().values().stream().filter(j->j.area.equals(a.id())&&j.pass.equals(pass)).reduce((x,y)->y).orElseThrow(()->new IllegalStateException("No owned "+pass+" snapshot"));d.jobs().put(id,d.jobs().get(id).withSnapshot(journal.id));d.changed();}}
    public static void process(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job job,int budget){var a=WorldPrepRuntime.requireArea(d,job.area());String pass=pass(job.operation());var bd=data(level);if(job.operation().name().startsWith("ROLLBACK")){rollback(level,d,bd,id,job,a,pass,budget);return;}String key=BlockWorldPrepData.planKey(a.id(),pass);var plan=bd.plans().get(key);if(job.operation().name().startsWith("PREVIEW")&&job.cursor()==0){plan=new BlockWorldPrepData.Plan(a.id(),pass,"development",input(level,d,a,pass),"");bd.plans().put(key,plan);bd.changed();}if(isApply(job.operation()))plan=requirePlan(level,d,a,pass);long height=level.getMaxBuildHeight()-level.getMinBuildHeight(),width=(long)a.maxX()-a.minX()+1,depth=(long)a.maxZ()-a.minZ()+1,total=width*depth*height,cursor=job.cursor();for(int n=0;n<budget&&cursor<total;n++,cursor++){int y=level.getMinBuildHeight()+(int)(cursor%height);long column=cursor/height;int x=a.minX()+(int)(column%width),z=a.minZ()+(int)(column/width);if(job.operation().name().startsWith("PREVIEW"))preview(level,d,plan,a,pass,x,y,z);else apply(level,d,bd,plan,d.jobs().get(id),a,x,y,z);d.jobs().put(id,d.jobs().get(id).withCursor(cursor+1));d.changed();}if(cursor>=total){if(job.operation().name().startsWith("PREVIEW")){plan.fingerprint=fingerprint(plan);if(pass.equals("GEOLOGY"))bd.plans().remove(BlockWorldPrepData.planKey(a.id(),"ORES"));bd.changed();}d.jobs().put(id,d.jobs().get(id).withState(WorldPrepSavedData.JobState.COMPLETED));d.changed();}}
    private static void preview(ServerLevel l,WorldPrepSavedData d,BlockWorldPrepData.Plan p,WorldPrepSavedData.Area a,String pass,int x,int y,int z){var pos=new BlockPos(x,y,z);var state=l.getBlockState(pos);boolean protectedAt=d.protectedBlock(a.dimension(),x,z)||l.getBlockEntity(pos)!=null;if(pass.equals("GEOLOGY")){if(!state.is(GEOLOGY)){if(protectedAt)p.skipped++;return;}p.eligible++;if(protectedAt){p.skipped++;return;}var province=GeologyPlanner.province(l.getSeed(),x,y,z);String target=GeologyPlanner.replacement(l.getSeed(),x,y,z,province);if(!id(state).equals(target))p.changes.put(BlockWorldPrepData.posKey(x,y,z),new BlockWorldPrepData.Change(x,y,z,encode(state),target,province.name()));}else{boolean stone=state.is(STONE),deep=state.is(DEEPSLATE);if(!stone&&!deep){if(protectedAt)p.skipped++;return;}p.eligible++;if(protectedAt){p.skipped++;return;}for(var ore:ORES)if(y>=ore.min&&y<=ore.max&&Math.floorMod(GeologyPlanner.mix(l.getSeed()^ore.salt^x*31L^y*131L^z*8191L),ore.rarity)==0){String target="minecraft:"+(deep?ore.deep:ore.stone);p.changes.put(BlockWorldPrepData.posKey(x,y,z),new BlockWorldPrepData.Change(x,y,z,encode(state),target,ore.name));break;}}}
    private static void apply(ServerLevel l,WorldPrepSavedData d,BlockWorldPrepData bd,BlockWorldPrepData.Plan p,WorldPrepSavedData.Job job,WorldPrepSavedData.Area a,int x,int y,int z){var c=p.changes.get(BlockWorldPrepData.posKey(x,y,z));if(c==null)return;var pos=new BlockPos(x,y,z);if(d.protectedBlock(a.dimension(),x,z)||l.getBlockEntity(pos)!=null)return;var current=l.getBlockState(pos);boolean valid=p.pass.equals("GEOLOGY")?current.is(GEOLOGY):(current.is(STONE)||current.is(DEEPSLATE))&&validOreTarget(c.applied(),y);if(!valid||!encode(current).equals(c.before()))return;var journal=bd.journals().get(job.snapshotId());if(journal==null||!journal.fingerprint.equals(p.fingerprint))throw new IllegalStateException("Snapshot ownership mismatch");journal.changes.put(BlockWorldPrepData.posKey(x,y,z),c);bd.changed();l.getDataStorage().save();l.setBlock(pos,decode(c.applied()),Block.UPDATE_CLIENTS);l.getChunkAt(pos).setUnsaved(true);}
    private static void rollback(ServerLevel l,WorldPrepSavedData d,BlockWorldPrepData bd,UUID id,WorldPrepSavedData.Job job,WorldPrepSavedData.Area a,String pass,int budget){var j=bd.journals().get(job.snapshotId());if(j==null||!j.area.equals(a.id())||!j.pass.equals(pass))throw new IllegalStateException("Snapshot ownership mismatch");var cells=new ArrayList<>(j.changes.values());cells.sort(Comparator.comparingInt(BlockWorldPrepData.Change::z).thenComparingInt(BlockWorldPrepData.Change::x).thenComparingInt(BlockWorldPrepData.Change::y));long cursor=job.cursor();for(int n=0;n<budget&&cursor<cells.size();n++,cursor++){var c=cells.get((int)cursor);if(c.x()<a.minX()||c.x()>a.maxX()||c.z()<a.minZ()||c.z()>a.maxZ())throw new IllegalStateException("Journal outside area");var pos=new BlockPos(c.x(),c.y(),c.z());if(d.protectedBlock(a.dimension(),c.x(),c.z()))throw new IllegalStateException("Rollback location is protected");if(!encode(l.getBlockState(pos)).equals(c.applied()))throw new IllegalStateException("Rollback ownership ambiguous at "+pos.toShortString());l.setBlock(pos,decode(c.before()),Block.UPDATE_CLIENTS);l.getChunkAt(pos).setUnsaved(true);d.jobs().put(id,d.jobs().get(id).withCursor(cursor+1));d.changed();}if(cursor>=cells.size()){d.jobs().put(id,d.jobs().get(id).withState(WorldPrepSavedData.JobState.COMPLETED));d.changed();}}
    private static boolean validOreTarget(String target,int y){for(var ore:ORES)if((target.equals("minecraft:"+ore.stone)||target.equals("minecraft:"+ore.deep))&&y>=ore.min&&y<=ore.max)return true;return false;}
    private static BlockWorldPrepData.Plan requirePlan(ServerLevel l,WorldPrepSavedData d,WorldPrepSavedData.Area a,String pass){var p=data(l).plans().get(BlockWorldPrepData.planKey(a.id(),pass));if(p==null||p.fingerprint.isEmpty())throw new IllegalStateException("No persisted "+pass+" preview");if(!p.input.equals(input(l,d,a,pass)))throw new IllegalStateException("Stale "+pass+" preview");if(pass.equals("ORES")&&!hasAppliedGeology(data(l),a.id()))throw new IllegalStateException("ORES requires applied GEOLOGY");return p;}
    private static boolean hasAppliedGeology(BlockWorldPrepData d,String area){return d.journals().values().stream().anyMatch(j->j.area.equals(area)&&j.pass.equals("GEOLOGY"));}
    public static String inputIdentity(ServerLevel l,WorldPrepSavedData d,WorldPrepSavedData.Area a,String pass){return input(l,d,a,pass);}
    public static void seal(BlockWorldPrepData.Plan plan){plan.fingerprint=fingerprint(plan);}
    public static String stateString(BlockState state){return encode(state);}
    private static String input(ServerLevel l,WorldPrepSavedData d,WorldPrepSavedData.Area a,String pass){long protections=d.protections().values().stream().filter(p->p.dimension().equals(a.dimension())).mapToLong(Object::hashCode).sum();String geology=pass.equals("ORES")?java.util.Optional.ofNullable(data(l).plans().get(BlockWorldPrepData.planKey(a.id(),"GEOLOGY"))).map(p->p.fingerprint).orElse(""):"";return a.dimension()+":"+a.minX()+":"+a.minZ()+":"+a.maxX()+":"+a.maxZ()+":"+l.getSeed()+":"+protections+":"+geology;}
    private static String fingerprint(BlockWorldPrepData.Plan p){String changes=PlanFingerprint.of(p.changes.values().stream().map(c->c.x()+","+c.y()+","+c.z()+","+c.before()+","+c.applied()).sorted().toArray(String[]::new)).value();return PlanFingerprint.of(p.input,changes).value();}
    private static String pass(WorldPrepSavedData.Operation o){return o.name().contains("GEOLOGY")?"GEOLOGY":"ORES";}private static boolean isApply(WorldPrepSavedData.Operation o){return o.name().startsWith("APPLY");}private static boolean isRollback(WorldPrepSavedData.Operation o){return o.name().startsWith("ROLLBACK");}
    private static TagKey<Block> tag(String path){return BlockTags.create(ResourceLocation.fromNamespaceAndPath("proutlost",path));}private static String id(BlockState s){return BuiltInRegistries.BLOCK.getKey(s.getBlock()).toString();}
    private static String encode(BlockState s){var b=new StringBuilder(id(s));if(!s.getValues().isEmpty()){b.append('[');s.getValues().entrySet().stream().sorted(Comparator.comparing(e->e.getKey().getName())).forEach(e->b.append(e.getKey().getName()).append('=').append(valueName(e.getKey(),e.getValue())).append(','));b.setCharAt(b.length()-1,']');}return b.toString();}
    @SuppressWarnings({"rawtypes","unchecked"}) private static String valueName(Property p,Comparable v){return p.getName(v);}
    @SuppressWarnings({"rawtypes","unchecked"}) private static BlockState decode(String text){int bracket=text.indexOf('[');String name=bracket<0?text:text.substring(0,bracket);BlockState state=BuiltInRegistries.BLOCK.get(ResourceLocation.parse(name)).defaultBlockState();if(bracket>=0){for(String pair:text.substring(bracket+1,text.length()-1).split(",")){String[] kv=pair.split("=",2);Property p=state.getBlock().getStateDefinition().getProperty(kv[0]);if(p==null||p.getValue(kv[1]).isEmpty())throw new IllegalStateException("Invalid persisted BlockState "+text);state=state.setValue(p,(Comparable)p.getValue(kv[1]).get());}}return state;}private BlockMutationRuntime(){}
}
