package fr.proutlost.worldprep.runtime;

import fr.proutlost.worldprep.WorldPrepConfig;
import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.plan.BiomeBounds;
import fr.proutlost.worldprep.plan.BiomePlanGuard;
import fr.proutlost.worldprep.plan.PlanFingerprint;
import fr.proutlost.worldprep.plan.PlanIdentity;
import fr.proutlost.worldprep.world.ServerExistingChunkAccess;
import net.minecraft.core.QuartPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.chunk.LevelChunk;
import net.neoforged.neoforge.event.tick.ServerTickEvent;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.UUID;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.io.IOException;
import fr.proutlost.worldprep.pipeline.PassId;
import fr.proutlost.worldprep.storage.PagedPlanStore;
import fr.proutlost.worldprep.storage.PlanManifest;

/** Server-thread, cell-budgeted and restart-safe job executor. It creates no force-load tickets. */
public final class WorldPrepRuntime {
    public static WorldPrepSavedData data(ServerLevel level){return level.getDataStorage().computeIfAbsent(WorldPrepSavedData.FACTORY,WorldPrepSavedData.FILE_ID);}
    public static UUID enqueue(ServerLevel level,WorldPrepSavedData.Operation op,String areaId){
        if(op.name().startsWith("ROLLBACK"))throw new IllegalArgumentException("Rollback requires an exact snapshot id");
        return enqueue(level,op,areaId,null);
    }
    public static UUID enqueueRollback(ServerLevel level,WorldPrepSavedData.Operation op,String areaId,UUID snapshotId){
        if(!op.name().startsWith("ROLLBACK"))throw new IllegalArgumentException("Operation is not rollback");
        return enqueue(level,op,areaId,java.util.Objects.requireNonNull(snapshotId,"snapshotId"));
    }
    private static UUID enqueue(ServerLevel level,WorldPrepSavedData.Operation op,String areaId,UUID snapshot){requireEnabled();var d=data(level);var area=requireArea(d,areaId);if(!area.dimension().equals(level.dimension().location().toString()))throw new IllegalStateException("Area belongs to another dimension");if(op.name().startsWith("APPLY")||op.name().startsWith("ROLLBACK"))assertUnlocked(d,area);UUID id=UUID.randomUUID();d.jobs().put(id,new WorldPrepSavedData.Job(id,op,areaId,WorldPrepSavedData.JobState.QUEUED,0,"",snapshot));d.changed();if(BlockMutationRuntime.isBlockOperation(op))BlockMutationRuntime.prepare(level,d,id,op,area);return id;}
    public static void tick(ServerTickEvent.Post event){if(!WorldPrepConfig.ENABLED.get())return;for(ServerLevel level:event.getServer().getAllLevels())tickLevel(level,WorldPrepConfig.CELLS_PER_TICK.get());}
    /** Runs one persisted job slice; exposed so runtime acceptance tests use the real executor. */
    public static void tickLevel(ServerLevel level,int budget){requireEnabled();var d=data(level);var entry=d.jobs().entrySet().stream().filter(e->e.getValue().state()==WorldPrepSavedData.JobState.RUNNING||e.getValue().state()==WorldPrepSavedData.JobState.QUEUED).findFirst().orElse(null);if(entry==null)return;var j=entry.getValue();if(j.state()==WorldPrepSavedData.JobState.QUEUED){j=j.withState(WorldPrepSavedData.JobState.RUNNING);entry.setValue(j);d.changed();}try{process(level,d,entry.getKey(),j,budget);}catch(Exception ex){var current=d.jobs().get(entry.getKey());d.jobs().put(entry.getKey(),current.failed(ex.getClass().getSimpleName()+": "+ex.getMessage()));d.changed();}}
    private static void process(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job job,int budget){if(BlockMutationRuntime.isBlockOperation(job.operation())){BlockMutationRuntime.process(level,d,id,job,budget);return;}var area=requireArea(d,job.area());var bounds=BiomeBounds.inside(area);if(job.operation()==WorldPrepSavedData.Operation.ROLLBACK_BIOMES){rollback(level,d,id,job,budget,area,bounds);return;}var plan=d.plans().get(area.id());if(job.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES&&job.cursor()==0){plan=new WorldPrepSavedData.Plan(area.id(),PlanIdentity.capture(level,d,area),"");publishBiome(level,d,area,bounds,plan);d.plans().put(area.id(),plan);d.jobs().put(id,job.withCursor(plan.entryCount).withState(WorldPrepSavedData.JobState.COMPLETED));d.changed();return;}if(job.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES){if(plan==null||plan.fingerprint.isEmpty())throw new IllegalStateException("No persisted preview");if(plan.planId==null)publishBiome(level,d,area,bounds,plan);PlanIdentity.requireCurrent(plan.input,PlanIdentity.capture(level,d,area));var manifest=biomeManifest(level,plan);var activePlan=plan;if(job.snapshotId()==null){UUID snapshotId=UUID.randomUUID();var snapshot=new WorldPrepSavedData.Snapshot(snapshotId,id,plan.planId,area.dimension(),area.id(),"BIOMES",plan.fingerprint);RuntimeBiomeJournal.initialize(level,snapshot);d.snapshots().put(snapshotId,snapshot);job=job.withSnapshot(snapshotId);d.jobs().put(id,job);d.changed();level.getDataStorage().save();}var activeSnapshot=validateSnapshot(d,job,area,plan);reconcileBiomeApply(level,d,area,activeSnapshot);long durable=activeSnapshot.pageCount;if(durable>plan.entryCount)throw new IllegalStateException("Biome journal exceeds exact plan");job=job.withCursor(durable);d.jobs().put(id,job);var touched=new LinkedHashSet<LevelChunk>();long start=durable;long[] sequence={start};try{var active=job;PagedPlanStore.readRange(RuntimePlanStore.directory(level,plan.planId),manifest,RuntimePlanStore.BIOME_CODEC,start,budget,cell->{if(applyPlannedCell(level,d,area,activePlan,d.snapshots().get(active.snapshotId()),cell,sequence[0]++))touched.add(ServerExistingChunkAccess.requireChunk(level,QuartPos.toBlock(cell.quartX())>>4,QuartPos.toBlock(cell.quartZ())>>4));var current=d.jobs().get(id);d.jobs().put(id,current.withCursor(current.cursor()+1));d.changed();});}catch(IOException e){throw new IllegalStateException("Paged biome plan validation failed",e);}BiomeRuntime.refresh(level,touched);job=d.jobs().get(id);if(job.cursor()>=plan.entryCount)d.jobs().put(id,job.withState(WorldPrepSavedData.JobState.COMPLETED));d.changed();}}
    public static boolean applyPlannedCell(ServerLevel level,WorldPrepSavedData d,WorldPrepSavedData.Area area,WorldPrepSavedData.Plan plan,WorldPrepSavedData.Snapshot snapshot,WorldPrepSavedData.BiomeCell cell){return applyPlannedCell(level,d,area,plan,snapshot,cell,0);}
    private static boolean applyPlannedCell(ServerLevel level,WorldPrepSavedData d,WorldPrepSavedData.Area area,WorldPrepSavedData.Plan plan,WorldPrepSavedData.Snapshot snapshot,WorldPrepSavedData.BiomeCell cell,long sequence){var bounds=BiomeBounds.inside(area);if(!bounds.contains(cell.quartX(),cell.quartZ())||!bounds.footprintInside(area,cell.quartX(),cell.quartZ()))throw new IllegalStateException("Planned cell outside area");PlanIdentity.requireCurrent(plan.input,PlanIdentity.capture(level,d,area));int bx=QuartPos.toBlock(cell.quartX())+2,bz=QuartPos.toBlock(cell.quartZ())+2;ServerExistingChunkAccess.requireBlock(level,area,bx,level.getMinBuildHeight(),bz);BiomePlanGuard.requireCurrent(cell.terrainSignature(),MinecraftTerrainSampler.sample(level,bx,bz).signature());if(d.protectedAt(area.dimension(),cell.quartX(),cell.quartZ()))throw new IllegalStateException("Sealed biome mutation is protected");requireSnapshotOwnership(snapshot,area,plan.fingerprint);var proposed=BiomeRuntime.inspectColumn(level,cell.quartX(),cell.quartZ(),cell.biome());var durable=RuntimeBiomeJournal.publishOrRead(level,snapshot,proposed);d.changed();level.getDataStorage().save();for(var owned:durable)BiomeRuntime.applyOwnedCell(level,owned);return true;}
    private static void rollback(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job job,int budget,WorldPrepSavedData.Area area,BiomeBounds bounds){var snapshot=validateSnapshot(d,job,area,d.plans().get(area.id()));RuntimeBiomeJournal.requireManifest(level,snapshot);preflightBiomeRollback(level,d,area,bounds,snapshot);int[] remaining={Math.max(1,budget)},restored={0};boolean[] pending={false};var touched=new LinkedHashSet<LevelChunk>();RuntimeBiomeJournal.visit(level,snapshot,(sequence,cells)->{for(var cell:cells){String current=BiomeRuntime.biomeId(level,cell.quartX(),cell.quartY(),cell.quartZ());if(current.equals(cell.appliedBiome())){if(remaining[0]>0){BiomeRuntime.restoreOwnedCell(level,cell);touched.add(ServerExistingChunkAccess.requireChunk(level,QuartPos.toBlock(cell.quartX())>>4,QuartPos.toBlock(cell.quartZ())>>4));remaining[0]--;restored[0]++;}else pending[0]=true;}}});BiomeRuntime.refresh(level,touched);var advanced=job.withCursor(job.cursor()+restored[0]);if(!pending[0])advanced=advanced.withState(WorldPrepSavedData.JobState.COMPLETED);d.jobs().put(id,advanced);d.changed();level.getDataStorage().save();}
    private static void preflightBiomeRollback(ServerLevel level,WorldPrepSavedData d,WorldPrepSavedData.Area area,BiomeBounds bounds,WorldPrepSavedData.Snapshot snapshot){RuntimeBiomeJournal.visit(level,snapshot,(sequence,cells)->{for(var cell:cells){if(!bounds.contains(cell.quartX(),cell.quartZ())||!bounds.footprintInside(area,cell.quartX(),cell.quartZ()))throw new IllegalStateException("Snapshot cell outside owned area");if(d.protectedAt(area.dimension(),cell.quartX(),cell.quartZ()))throw new IllegalStateException("Rollback cell is now protected");String current=BiomeRuntime.biomeId(level,cell.quartX(),cell.quartY(),cell.quartZ());if(!current.equals(cell.beforeBiome())&&!current.equals(cell.appliedBiome()))throw new IllegalStateException("Biome ownership conflict during rollback");}});}
    private static void reconcileBiomeApply(ServerLevel level,WorldPrepSavedData d,WorldPrepSavedData.Area area,WorldPrepSavedData.Snapshot snapshot){if(snapshot.pageCount==0&&!java.nio.file.Files.exists(fr.proutlost.worldprep.storage.PagedJournalStore.manifestPath(RuntimeBiomeJournal.directory(level,snapshot.id))))return;RuntimeBiomeJournal.requireManifest(level,snapshot);RuntimeBiomeJournal.visit(level,snapshot,(sequence,cells)->{for(var cell:cells){if(d.protectedAt(area.dimension(),cell.quartX(),cell.quartZ()))throw new IllegalStateException("Journaled biome mutation is protected");String current=BiomeRuntime.biomeId(level,cell.quartX(),cell.quartY(),cell.quartZ());if(!current.equals(cell.beforeBiome())&&!current.equals(cell.appliedBiome()))throw new IllegalStateException("Biome ownership conflict during apply recovery");}});RuntimeBiomeJournal.visit(level,snapshot,(sequence,cells)->{for(var cell:cells)BiomeRuntime.applyOwnedCell(level,cell);});d.changed();}
    private static WorldPrepSavedData.Snapshot validateSnapshot(WorldPrepSavedData d,WorldPrepSavedData.Job job,WorldPrepSavedData.Area area,WorldPrepSavedData.Plan plan){if(job.snapshotId()==null)throw new IllegalStateException("Job has no snapshot ownership");var s=d.snapshots().get(job.snapshotId());if(s==null||plan==null)throw new IllegalStateException("Snapshot ownership mismatch");requireSnapshotOwnership(s,area,plan.fingerprint);if(job.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES&&!s.jobId.equals(job.id()))throw new IllegalStateException("Snapshot apply-job ownership mismatch");return s;}
    public static void requireSnapshotOwnership(WorldPrepSavedData.Snapshot s,WorldPrepSavedData.Area area,String fingerprint){if(!s.dimension.equals(area.dimension())||!s.area.equals(area.id())||!s.pass.equals("BIOMES")||!s.planFingerprint.equals(fingerprint))throw new IllegalStateException("Snapshot ownership mismatch");}
    private static String chooseBiome(WorldPrepSavedData d,MinecraftTerrainSampler.Sample s,long seed,int x,int z){var o=d.overrides().get(WorldPrepSavedData.cellKey(x,z));if(o!=null&&o.exactBiome()!=null)return o.exactBiome();if(o!=null&&o.palette()!=null)return palette(o.palette(),s);if(s.waterDepth()>20)return"minecraft:deep_ocean";if(s.waterDepth()>6)return"minecraft:ocean";if(s.waterDepth()>0)return"minecraft:lukewarm_ocean";if(s.surfaceY()>=133)return"minecraft:jagged_peaks";if(s.slope()>=8)return"minecraft:windswept_hills";if(s.coastDistance()<=4)return s.slope()>3?"minecraft:stony_shore":"minecraft:beach";long v=seed^((long)x*341873128712L)^((long)z*132897987541L);return(v&3)==0?"minecraft:forest":"minecraft:plains";}
    private static String palette(String p,MinecraftTerrainSampler.Sample s){return switch(p){case"coastal"->"minecraft:beach";case"lowland_forest"->"minecraft:forest";case"open_lowland"->"minecraft:plains";case"marine_deep"->"minecraft:deep_ocean";case"marine"->"minecraft:ocean";default->throw new IllegalStateException("Unknown palette override "+p);};}
    private static String fingerprint(WorldPrepSavedData.Plan p){var parts=p.cells.values().stream().sorted(Comparator.comparingInt(WorldPrepSavedData.BiomeCell::quartZ).thenComparingInt(WorldPrepSavedData.BiomeCell::quartX)).map(c->c.quartX()+","+c.quartZ()+","+c.biome()+","+c.terrainSignature()).toArray(String[]::new);String cells=PlanFingerprint.of(parts).value();return PlanFingerprint.of(PlanIdentity.fingerprint(p.input),cells).value();}
    private static void publishBiome(ServerLevel level,WorldPrepSavedData d,WorldPrepSavedData.Area area,BiomeBounds bounds,WorldPrepSavedData.Plan plan){try{Iterable<WorldPrepSavedData.BiomeCell> entries=plan.cells.isEmpty()?()->new Iterator<>(){long cursor;public boolean hasNext(){return cursor<bounds.cells();}public WorldPrepSavedData.BiomeCell next(){if(!hasNext())throw new NoSuchElementException();int qx=bounds.minQuartX()+(int)(cursor%bounds.width()),qz=bounds.minQuartZ()+(int)(cursor++/bounds.width());if(!bounds.footprintInside(area,qx,qz))throw new IllegalStateException("Bounds invariant failed");var sample=MinecraftTerrainSampler.sample(level,QuartPos.toBlock(qx)+2,QuartPos.toBlock(qz)+2);return new WorldPrepSavedData.BiomeCell(qx,qz,chooseBiome(d,sample,plan.input.seed(),qx,qz),sample.signature());}}:plan.cells.values();plan.planId=UUID.randomUUID();var publication=PagedPlanStore.publish(RuntimePlanStore.root(level),plan.planId,PassId.BIOMES,area.id(),area.dimension(),plan.input.profile(),PlanIdentity.fingerprint(plan.input),RuntimePlanStore.ENGINE_VERSION,RuntimePlanStore.PLANNER_VERSION,RuntimePlanStore.ENTRIES_PER_PAGE,entries,RuntimePlanStore.BIOME_CODEC);plan.entryCount=publication.manifest().pages().stream().mapToLong(PlanManifest.PageReference::entryCount).sum();plan.fingerprint=publication.manifest().rootFingerprint();plan.cells.clear();}catch(IOException e){throw new IllegalStateException("Biome plan publication failed",e);}}
    private static PlanManifest biomeManifest(ServerLevel level,WorldPrepSavedData.Plan plan){try{var m=PagedPlanStore.readManifest(RuntimePlanStore.directory(level,plan.planId));if(!m.planId().equals(plan.planId)||m.passId()!=PassId.BIOMES||!m.rootFingerprint().equals(plan.fingerprint))throw new IOException("Exact biome manifest mismatch");m.requireApplicable();return m;}catch(IOException e){throw new IllegalStateException("Sealed biome manifest unavailable",e);}}
    public static WorldPrepSavedData.Area requireArea(WorldPrepSavedData d,String id){var a=d.areas().get(id);if(a==null)throw new IllegalArgumentException("Unknown area "+id);return a;}public static void assertUnlocked(WorldPrepSavedData d,WorldPrepSavedData.Area requested){for(var j:d.jobs().values())if((j.operation().name().startsWith("APPLY")||j.operation().name().startsWith("ROLLBACK"))&&(j.state()==WorldPrepSavedData.JobState.QUEUED||j.state()==WorldPrepSavedData.JobState.RUNNING||j.state()==WorldPrepSavedData.JobState.PAUSED)&&requireArea(d,j.area()).overlaps(requested))throw new IllegalStateException("Overlapping destructive job "+j.id());}private static void requireEnabled(){if(!WorldPrepConfig.ENABLED.get())throw new IllegalStateException("WorldPrep is disabled by configuration");}private WorldPrepRuntime(){}
}
