package fr.proutlost.worldprep.runtime;

import fr.proutlost.worldprep.WorldPrepConfig;
import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.plan.PlanFingerprint;
import fr.proutlost.worldprep.plan.BiomePlanGuard;
import net.minecraft.core.QuartPos;
import net.minecraft.server.level.ServerLevel;
import net.neoforged.neoforge.event.tick.ServerTickEvent;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.UUID;

/** Server-thread, budgeted and restart-safe job executor. */
public final class WorldPrepRuntime {
    public static WorldPrepSavedData data(ServerLevel level){return level.getDataStorage().computeIfAbsent(WorldPrepSavedData.FACTORY,WorldPrepSavedData.FILE_ID);}
    public static UUID enqueue(ServerLevel level,WorldPrepSavedData.Operation op,String areaId){var d=data(level);var area=requireArea(d,areaId);if(op==WorldPrepSavedData.Operation.APPLY_BIOMES||op==WorldPrepSavedData.Operation.ROLLBACK_BIOMES)assertUnlocked(d,area);UUID id=UUID.randomUUID();d.jobs().put(id,new WorldPrepSavedData.Job(id,op,areaId,WorldPrepSavedData.JobState.QUEUED,0,""));d.changed();return id;}
    public static void tick(ServerTickEvent.Post event){for(ServerLevel level:event.getServer().getAllLevels())tickLevel(level,WorldPrepConfig.CELLS_PER_TICK.get());}
    static void tickLevel(ServerLevel level,int budget){var d=data(level);var entry=d.jobs().entrySet().stream().filter(e->e.getValue().state()==WorldPrepSavedData.JobState.RUNNING||e.getValue().state()==WorldPrepSavedData.JobState.QUEUED).findFirst().orElse(null);if(entry==null)return;var j=entry.getValue();if(j.state()==WorldPrepSavedData.JobState.QUEUED){j=j.withState(WorldPrepSavedData.JobState.RUNNING);entry.setValue(j);d.changed();}try{process(level,d,entry.getKey(),j,budget);}catch(Exception ex){entry.setValue(j.failed(ex.getClass().getSimpleName()+": "+ex.getMessage()));d.changed();}}
    private static void process(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job j,int budget){var a=requireArea(d,j.area());int minQx=QuartPos.fromBlock(a.minX()),maxQx=QuartPos.fromBlock(a.maxX()),minQz=QuartPos.fromBlock(a.minZ()),maxQz=QuartPos.fromBlock(a.maxZ());long width=(long)maxQx-minQx+1,total=width*((long)maxQz-minQz+1);if(j.operation()==WorldPrepSavedData.Operation.ROLLBACK_BIOMES){rollback(level,d,id,j,budget);return;}var plan=d.plans().get(a.id());if(j.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES&&j.cursor()==0){plan=new WorldPrepSavedData.Plan(a.id(),"proutlost:river_test",7640891576956012809L,"");d.plans().put(a.id(),plan);}if(j.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES){if(plan==null||plan.fingerprint.isEmpty())throw new IllegalStateException("No persisted preview");if(j.cursor()==0){d.snapshots().put(a.id(),new WorldPrepSavedData.Snapshot(a.id(),plan.fingerprint));d.changed();}}
        long cursor=j.cursor();for(int n=0;n<budget&&cursor<total;n++,cursor++){int qx=minQx+(int)(cursor%width),qz=minQz+(int)(cursor/width);int bx=QuartPos.toBlock(qx)+2,bz=QuartPos.toBlock(qz)+2;var sample=MinecraftTerrainSampler.sample(level,bx,bz);if(j.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES){String biome=chooseBiome(sample,plan.seed,qx,qz);plan.cells.put(WorldPrepSavedData.cellKey(qx,qz),new WorldPrepSavedData.BiomeCell(qx,qz,biome,sample.signature()));}else if(j.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES){var cell=plan.cells.get(WorldPrepSavedData.cellKey(qx,qz));if(cell==null)throw new IllegalStateException("Persisted plan cell missing");try{BiomePlanGuard.requireCurrent(cell.terrainSignature(),sample.signature());}catch(IllegalStateException stale){throw new IllegalStateException("PREVIEW STALE at "+bx+","+bz,stale);}var snapshot=d.snapshots().get(a.id());BiomeRuntime.captureColumn(level,snapshot,qx,qz);d.changed();level.getDataStorage().save();BiomeRuntime.writeColumn(level,qx,qz,cell.biome());BiomeRuntime.refresh(level,level.getChunk(bx>>4,bz>>4));}else MinecraftTerrainSampler.sample(level,bx,bz);}
        var next=j.withCursor(cursor);if(cursor>=total){if(j.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES)plan.fingerprint=fingerprint(plan);next=next.withState(WorldPrepSavedData.JobState.COMPLETED);}d.jobs().put(id,next);d.changed();}
    private static void rollback(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job j,int budget){var s=d.snapshots().get(j.area());if(s==null)throw new IllegalStateException("No rollback snapshot");var cells=new ArrayList<>(s.cells.values());long cursor=j.cursor();for(int n=0;n<budget&&cursor<cells.size();n++,cursor++)BiomeRuntime.restoreCell(level,cells.get((int)cursor));var next=j.withCursor(cursor);if(cursor>=cells.size())next=next.withState(WorldPrepSavedData.JobState.COMPLETED);d.jobs().put(id,next);d.changed();}
    private static String chooseBiome(MinecraftTerrainSampler.Sample s,long seed,int x,int z){if(s.waterDepth()>20)return "minecraft:deep_ocean";if(s.waterDepth()>6)return "minecraft:ocean";if(s.waterDepth()>0)return "minecraft:lukewarm_ocean";if(s.surfaceY()>=133)return "minecraft:jagged_peaks";if(s.slope()>=8)return "minecraft:windswept_hills";if(s.coastDistance()<=4)return s.slope()>3?"minecraft:stony_shore":"minecraft:beach";long v=seed^((long)x*341873128712L)^((long)z*132897987541L);return (v&3)==0?"minecraft:forest":"minecraft:plains";}
    private static String fingerprint(WorldPrepSavedData.Plan p){var parts=p.cells.values().stream().sorted(Comparator.comparingInt(WorldPrepSavedData.BiomeCell::quartZ).thenComparingInt(WorldPrepSavedData.BiomeCell::quartX)).map(c->c.quartX()+","+c.quartZ()+","+c.biome()+","+c.terrainSignature()).toArray(String[]::new);return PlanFingerprint.of(parts).value();}
    public static WorldPrepSavedData.Area requireArea(WorldPrepSavedData d,String id){var a=d.areas().get(id);if(a==null)throw new IllegalArgumentException("Unknown area "+id);return a;}
    public static void assertUnlocked(WorldPrepSavedData d,WorldPrepSavedData.Area requested){for(var j:d.jobs().values())if((j.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES||j.operation()==WorldPrepSavedData.Operation.ROLLBACK_BIOMES)&&(j.state()==WorldPrepSavedData.JobState.QUEUED||j.state()==WorldPrepSavedData.JobState.RUNNING||j.state()==WorldPrepSavedData.JobState.PAUSED)&&requireArea(d,j.area()).overlaps(requested))throw new IllegalStateException("Overlapping destructive job "+j.id());}
    private WorldPrepRuntime(){}
}
