package fr.proutlost.worldprep.runtime;

import fr.proutlost.worldprep.WorldPrepConfig;
import fr.proutlost.worldprep.persistence.WorldPrepSavedData;
import fr.proutlost.worldprep.plan.BiomeBounds;
import fr.proutlost.worldprep.plan.BiomePlanGuard;
import fr.proutlost.worldprep.plan.PlanFingerprint;
import fr.proutlost.worldprep.plan.PlanIdentity;
import net.minecraft.core.QuartPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.chunk.LevelChunk;
import net.neoforged.neoforge.event.tick.ServerTickEvent;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.UUID;

/** Server-thread, cell-budgeted and restart-safe job executor. It creates no force-load tickets. */
public final class WorldPrepRuntime {
    public static WorldPrepSavedData data(ServerLevel level){return level.getDataStorage().computeIfAbsent(WorldPrepSavedData.FACTORY,WorldPrepSavedData.FILE_ID);}
    public static UUID enqueue(ServerLevel level,WorldPrepSavedData.Operation op,String areaId){var d=data(level);var area=requireArea(d,areaId);if(!area.dimension().equals(level.dimension().location().toString()))throw new IllegalStateException("Area belongs to another dimension");if(op.name().startsWith("APPLY")||op.name().startsWith("ROLLBACK"))assertUnlocked(d,area);UUID id=UUID.randomUUID(),snapshot=null;if(op==WorldPrepSavedData.Operation.ROLLBACK_BIOMES)snapshot=latestOwnedSnapshot(d,area).id;d.jobs().put(id,new WorldPrepSavedData.Job(id,op,areaId,WorldPrepSavedData.JobState.QUEUED,0,"",snapshot));d.changed();if(BlockMutationRuntime.isBlockOperation(op))BlockMutationRuntime.prepare(level,d,id,op,area);return id;}
    public static void tick(ServerTickEvent.Post event){for(ServerLevel level:event.getServer().getAllLevels())tickLevel(level,WorldPrepConfig.CELLS_PER_TICK.get());}
    /** Runs one persisted job slice; exposed so runtime acceptance tests use the real executor. */
    public static void tickLevel(ServerLevel level,int budget){var d=data(level);var entry=d.jobs().entrySet().stream().filter(e->e.getValue().state()==WorldPrepSavedData.JobState.RUNNING||e.getValue().state()==WorldPrepSavedData.JobState.QUEUED).findFirst().orElse(null);if(entry==null)return;var j=entry.getValue();if(j.state()==WorldPrepSavedData.JobState.QUEUED){j=j.withState(WorldPrepSavedData.JobState.RUNNING);entry.setValue(j);d.changed();}try{process(level,d,entry.getKey(),j,budget);}catch(Exception ex){var current=d.jobs().get(entry.getKey());d.jobs().put(entry.getKey(),current.failed(ex.getClass().getSimpleName()+": "+ex.getMessage()));d.changed();}}
    private static void process(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job job,int budget){if(BlockMutationRuntime.isBlockOperation(job.operation())){BlockMutationRuntime.process(level,d,id,job,budget);return;}var area=requireArea(d,job.area());var bounds=BiomeBounds.inside(area);if(job.operation()==WorldPrepSavedData.Operation.ROLLBACK_BIOMES){rollback(level,d,id,job,budget,area,bounds);return;}var plan=d.plans().get(area.id());if(job.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES&&job.cursor()==0){plan=new WorldPrepSavedData.Plan(area.id(),PlanIdentity.capture(level,d,area),"");d.plans().put(area.id(),plan);}if(job.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES){if(plan==null||plan.fingerprint.isEmpty())throw new IllegalStateException("No persisted preview");PlanIdentity.requireCurrent(plan.input,PlanIdentity.capture(level,d,area));if(job.cursor()==0){UUID snapshotId=UUID.randomUUID();var snapshot=new WorldPrepSavedData.Snapshot(snapshotId,id,area.dimension(),area.id(),"BIOMES",plan.fingerprint);d.snapshots().put(snapshotId,snapshot);job=job.withSnapshot(snapshotId);d.jobs().put(id,job);d.changed();level.getDataStorage().save();}validateSnapshot(d,job,area,plan);}
        long cursor=job.cursor(),total=bounds.cells();var touched=new LinkedHashSet<LevelChunk>();for(int n=0;n<budget&&cursor<total;n++){int qx=bounds.minQuartX()+(int)(cursor%bounds.width()),qz=bounds.minQuartZ()+(int)(cursor/bounds.width());if(!bounds.footprintInside(area,qx,qz))throw new IllegalStateException("Bounds invariant failed");int bx=QuartPos.toBlock(qx)+2,bz=QuartPos.toBlock(qz)+2;var sample=MinecraftTerrainSampler.sample(level,bx,bz);
            if(job.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES){String biome=chooseBiome(d,sample,plan.input.seed(),qx,qz);plan.cells.put(WorldPrepSavedData.cellKey(qx,qz),new WorldPrepSavedData.BiomeCell(qx,qz,biome,sample.signature()));}
            else if(job.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES){var cell=plan.cells.get(WorldPrepSavedData.cellKey(qx,qz));if(cell==null)throw new IllegalStateException("Persisted plan cell missing");if(applyPlannedCell(level,d,area,plan,d.snapshots().get(job.snapshotId()),cell))touched.add(level.getChunk(bx>>4,bz>>4));}
            cursor++;job=job.withCursor(cursor);d.jobs().put(id,job);d.changed();}
        BiomeRuntime.refresh(level,touched);if(cursor>=total){if(job.operation()==WorldPrepSavedData.Operation.PREVIEW_BIOMES)plan.fingerprint=fingerprint(plan);d.jobs().put(id,job.withState(WorldPrepSavedData.JobState.COMPLETED));d.changed();}}
    public static boolean applyPlannedCell(ServerLevel level,WorldPrepSavedData d,WorldPrepSavedData.Area area,WorldPrepSavedData.Plan plan,WorldPrepSavedData.Snapshot snapshot,WorldPrepSavedData.BiomeCell cell){var bounds=BiomeBounds.inside(area);if(!bounds.contains(cell.quartX(),cell.quartZ())||!bounds.footprintInside(area,cell.quartX(),cell.quartZ()))throw new IllegalStateException("Planned cell outside area");PlanIdentity.requireCurrent(plan.input,PlanIdentity.capture(level,d,area));int bx=QuartPos.toBlock(cell.quartX())+2,bz=QuartPos.toBlock(cell.quartZ())+2;BiomePlanGuard.requireCurrent(cell.terrainSignature(),MinecraftTerrainSampler.sample(level,bx,bz).signature());if(d.protectedAt(area.dimension(),cell.quartX(),cell.quartZ()))return false;requireSnapshotOwnership(snapshot,area,plan.fingerprint);BiomeRuntime.captureColumn(level,snapshot,cell.quartX(),cell.quartZ(),cell.biome());d.changed();level.getDataStorage().save();BiomeRuntime.writeColumn(level,cell.quartX(),cell.quartZ(),cell.biome());return true;}
    private static void rollback(ServerLevel level,WorldPrepSavedData d,UUID id,WorldPrepSavedData.Job job,int budget,WorldPrepSavedData.Area area,BiomeBounds bounds){var snapshot=validateSnapshot(d,job,area,d.plans().get(area.id()));var cells=new ArrayList<>(snapshot.cells.values());long cursor=job.cursor();var touched=new LinkedHashSet<LevelChunk>();for(int n=0;n<budget&&cursor<cells.size();n++){var cell=cells.get((int)cursor);if(!bounds.contains(cell.quartX(),cell.quartZ())||!bounds.footprintInside(area,cell.quartX(),cell.quartZ()))throw new IllegalStateException("Snapshot cell outside owned area");if(d.protectedAt(area.dimension(),cell.quartX(),cell.quartZ()))throw new IllegalStateException("Rollback cell is now protected");BiomeRuntime.restoreOwnedCell(level,cell);touched.add(level.getChunk(QuartPos.toBlock(cell.quartX())>>4,QuartPos.toBlock(cell.quartZ())>>4));cursor++;job=job.withCursor(cursor);d.jobs().put(id,job);d.changed();}BiomeRuntime.refresh(level,touched);if(cursor>=cells.size())d.jobs().put(id,job.withState(WorldPrepSavedData.JobState.COMPLETED));d.changed();}
    private static WorldPrepSavedData.Snapshot validateSnapshot(WorldPrepSavedData d,WorldPrepSavedData.Job job,WorldPrepSavedData.Area area,WorldPrepSavedData.Plan plan){if(job.snapshotId()==null)throw new IllegalStateException("Job has no snapshot ownership");var s=d.snapshots().get(job.snapshotId());if(s==null||plan==null)throw new IllegalStateException("Snapshot ownership mismatch");requireSnapshotOwnership(s,area,plan.fingerprint);if(job.operation()==WorldPrepSavedData.Operation.APPLY_BIOMES&&!s.jobId.equals(job.id()))throw new IllegalStateException("Snapshot apply-job ownership mismatch");return s;}
    public static void requireSnapshotOwnership(WorldPrepSavedData.Snapshot s,WorldPrepSavedData.Area area,String fingerprint){if(!s.dimension.equals(area.dimension())||!s.area.equals(area.id())||!s.pass.equals("BIOMES")||!s.planFingerprint.equals(fingerprint))throw new IllegalStateException("Snapshot ownership mismatch");}
    private static WorldPrepSavedData.Snapshot latestOwnedSnapshot(WorldPrepSavedData d,WorldPrepSavedData.Area a){return d.snapshots().values().stream().filter(s->s.dimension.equals(a.dimension())&&s.area.equals(a.id())&&s.pass.equals("BIOMES")).reduce((x,y)->y).orElseThrow(()->new IllegalStateException("No owned biome snapshot"));}
    private static String chooseBiome(WorldPrepSavedData d,MinecraftTerrainSampler.Sample s,long seed,int x,int z){var o=d.overrides().get(WorldPrepSavedData.cellKey(x,z));if(o!=null&&o.exactBiome()!=null)return o.exactBiome();if(o!=null&&o.palette()!=null)return palette(o.palette(),s);if(s.waterDepth()>20)return"minecraft:deep_ocean";if(s.waterDepth()>6)return"minecraft:ocean";if(s.waterDepth()>0)return"minecraft:lukewarm_ocean";if(s.surfaceY()>=133)return"minecraft:jagged_peaks";if(s.slope()>=8)return"minecraft:windswept_hills";if(s.coastDistance()<=4)return s.slope()>3?"minecraft:stony_shore":"minecraft:beach";long v=seed^((long)x*341873128712L)^((long)z*132897987541L);return(v&3)==0?"minecraft:forest":"minecraft:plains";}
    private static String palette(String p,MinecraftTerrainSampler.Sample s){return switch(p){case"coastal"->"minecraft:beach";case"lowland_forest"->"minecraft:forest";case"open_lowland"->"minecraft:plains";case"marine_deep"->"minecraft:deep_ocean";case"marine"->"minecraft:ocean";default->throw new IllegalStateException("Unknown palette override "+p);};}
    private static String fingerprint(WorldPrepSavedData.Plan p){var parts=p.cells.values().stream().sorted(Comparator.comparingInt(WorldPrepSavedData.BiomeCell::quartZ).thenComparingInt(WorldPrepSavedData.BiomeCell::quartX)).map(c->c.quartX()+","+c.quartZ()+","+c.biome()+","+c.terrainSignature()).toArray(String[]::new);String cells=PlanFingerprint.of(parts).value();return PlanFingerprint.of(PlanIdentity.fingerprint(p.input),cells).value();}
    public static WorldPrepSavedData.Area requireArea(WorldPrepSavedData d,String id){var a=d.areas().get(id);if(a==null)throw new IllegalArgumentException("Unknown area "+id);return a;}public static void assertUnlocked(WorldPrepSavedData d,WorldPrepSavedData.Area requested){for(var j:d.jobs().values())if((j.operation().name().startsWith("APPLY")||j.operation().name().startsWith("ROLLBACK"))&&(j.state()==WorldPrepSavedData.JobState.QUEUED||j.state()==WorldPrepSavedData.JobState.RUNNING||j.state()==WorldPrepSavedData.JobState.PAUSED)&&requireArea(d,j.area()).overlaps(requested))throw new IllegalStateException("Overlapping destructive job "+j.id());}private WorldPrepRuntime(){}
}
